# Generated by Django 3.1.7 on 2021-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunsik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hansik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ilsik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jimtang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jokbal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jungsik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yasik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('predict', models.BigIntegerField()),
            ],
        ),
    ]
