# Generated by Django 3.1.7 on 2021-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunsik',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='etc',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hansik',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ilsik',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jimtang',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jokbal',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jungsik',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='yasik',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
