# Generated by Django 3.1.7 on 2021-04-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210421_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunsik',
            name='category',
            field=models.CharField(default='분식', max_length=20),
        ),
        migrations.AddField(
            model_name='cafe',
            name='category',
            field=models.CharField(default='카페/디저트', max_length=20),
        ),
        migrations.AddField(
            model_name='chicken',
            name='category',
            field=models.CharField(default='치킨', max_length=20),
        ),
        migrations.AddField(
            model_name='etc',
            name='category',
            field=models.CharField(default='기타', max_length=20),
        ),
        migrations.AddField(
            model_name='fastfood',
            name='category',
            field=models.CharField(default='패스트푸드', max_length=20),
        ),
        migrations.AddField(
            model_name='hansik',
            name='category',
            field=models.CharField(default='한식', max_length=20),
        ),
        migrations.AddField(
            model_name='ilsik',
            name='category',
            field=models.CharField(default='돈까스/일식', max_length=20),
        ),
        migrations.AddField(
            model_name='jimtang',
            name='category',
            field=models.CharField(default='찜/탕', max_length=20),
        ),
        migrations.AddField(
            model_name='jokbal',
            name='category',
            field=models.CharField(default='족발/보쌈', max_length=20),
        ),
        migrations.AddField(
            model_name='jungsik',
            name='category',
            field=models.CharField(default='중식', max_length=20),
        ),
        migrations.AddField(
            model_name='yasik',
            name='category',
            field=models.CharField(default='야식', max_length=20),
        ),
    ]
