# Generated by Django 3.1.7 on 2021-04-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210422_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunsik',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chicken',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='etc',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hansik',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ilsik',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jimtang',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jokbal',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jungsik',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yasik',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
